# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Goshmx
tagline:          'Blog personal'
description:      'Ideas, código y vida entre música binaria.'
url:              https://goshmx.com
baseurl:          https://goshmx.com/

author:
  name:           'Gosh Hernández'
  url:            https://twitter.com/gosh_

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/poole/hyde
